export const tags = [
  "UI Design",
  "UX Design",
  "Web Design",
  "App Design",
  "Motion Design",
  "Branding",
  "Typography",
  "Icon Design",
  "Illustration",
  "3D Design",
  "Print Design",
  "Packaging",
  "Product Design",
  "AR/VR Design",

  "Minimalist",
  "Abstract",
  "Retro",
  "Futuristic",
  "Cyberpunk",
  "Grunge",
  "Flat",
  "Skeuomorphic",
  "Hand-Drawn",
  "Isometric",
  "Photorealistic",
  "Vaporwave",
  "Surreal",
  "Fantasy",
  "Concept Art",

  "Landing Page",
  "Portfolio",
  "Dashboard",
  "Mobile App",
  "Icon Set",
  "Logo",
  "Poster",
  "T-Shirt Design",
  "Infographic",
  "NFT",
  "Game UI",
  "Social Media Post",
  "Ebook Cover",
  "Album Art",
  "UI Kit",

  "Daily UI",
  "Dark Mode",
  "Light Mode",
  "Prompt-to-Design",
  "Design Challenge",
  "Before & After",
  "Speed Art",
  "WIP",
  "Case Study",
  "Collab",
  "Fan Art",
  "Design System",
  "Grid Layout",
  "Custom Typeface"
];
