import { db } from './drizzle'; // Import your database instance
import { tags } from './schema'; // Import your tags table schema

export const seedTags = async () => {
  const tagData = [
    "2d",
    "3d",
    "3d art",
    "abstract",
    "adobe",
    "adobe illustrator",
    "adobe photoshop",
    "adobe xd",
    "advertising",
    "after effects",
    "agency",
    "ai",
    "android",
    "animal",
    "animation",
    "app",
    "app design",
    "apparel",
    "apple",
    "application",
    "architecture",
    "art",
    "art direction",
    "artist",
    "artwork",
    "background",
    "badge",
    "banner",
    "beauty",
    "beer",
    "bird",
    "black",
    "blender",
    "blockchain",
    "blog",
    "blue",
    "book",
    "brand",
    "brand design",
    "brand identity",
    "branding",
    "branding design",
    "brochure",
    "building",
    "business",
    "business card",
    "business logo",
    "button",
    "c4d",
    "calligraphy",
    "car",
    "card",
    "cards",
    "cartoon",
    "cat",
    "challenge",
    "character",
    "character design",
    "chart",
    "christmas",
    "cinema4d",
    "city",
    "clean",
    "clothing",
    "coffee",
    "color",
    "colorful",
    "colors",
    "company",
    "concept",
    "corporate",
    "cover",
    "creative",
    "creative logo",
    "crypto",
    "cute",
    "daily",
    "daily ui",
    "dark",
    "dashboard",
    "data",
    "design",
    "designer",
    "desktop",
    "digital",
    "digital art",
    "digital illustration",
    "digital marketing",
    "dog",
    "download",
    "drawing",
    "dribbble",
    "e commerce",
    "ecommerce",
    "editorial",
    "education",
    "elegant",
    "event",
    "fashion",
    "figma",
    "finance",
    "fintech",
    "fitness",
    "flat",
    "flat design",
    "flower",
    "flowers",
    "flyer",
    "font",
    "food",
    "football",
    "free",
    "freebie",
    "fun",
    "game",
    "gaming",
    "geometric",
    "gif",
    "girl",
    "gold",
    "gradient",
    "graphic",
    "graphic design",
    "graphics",
    "green",
    "grid",
    "halloween",
    "hand drawn",
    "hand lettering",
    "health",
    "healthcare",
    "home",
    "homepage",
    "house",
    "icon",
    "icons",
    "identity",
    "illustration",
    "illustration art",
    "illustrations",
    "illustrator",
    "infographic",
    "inspiration",
    "instagram",
    "interaction",
    "interface",
    "ios",
    "ipad",
    "iphone",
    "isometric",
    "kids",
    "label",
    "landing",
    "landing page",
    "landscape",
    "layout",
    "letter",
    "lettering",
    "light",
    "line",
    "login",
    "logo",
    "logo design",
    "logo designer",
    "logo mark",
    "logos",
    "logotype",
    "loop",
    "love",
    "magazine",
    "map",
    "mark",
    "marketing",
    "mascot",
    "medical",
    "menu",
    "minimal",
    "minimalism",
    "minimalist",
    "mobile",
    "mobile app",
    "mobile design",
    "mockup",
    "modern",
    "modern logo",
    "money",
    "monogram",
    "motion",
    "motion design",
    "motion graphics",
    "music",
    "nature",
    "nft",
    "orange",
    "packaging",
    "page",
    "painting",
    "pattern",
    "people",
    "photo",
    "photography",
    "photoshop",
    "pink",
    "portfolio",
    "portrait",
    "poster",
    "poster design",
    "presentation",
    "print",
    "print design",
    "procreate",
    "product",
    "product design",
    "profile",
    "prototype",
    "psd",
    "purple",
    "real estate",
    "red",
    "redesign",
    "render",
    "responsive",
    "restaurant",
    "retro",
    "saas",
    "script",
    "search",
    "shop",
    "shopping",
    "simple",
    "sketch",
    "skull",
    "social",
    "social media",
    "software",
    "space",
    "sport",
    "sports",
    "startup",
    "sticker",
    "store",
    "style",
    "summer",
    "symbol",
    "t shirt",
    "tech",
    "technology",
    "template",
    "texture",
    "travel",
    "tshirt",
    "type",
    "typeface",
    "typography",
    "ui",
    "ui design",
    "ui ux",
    "uidesign",
    "uiux",
    "user experience",
    "user interface",
    "ux",
    "ux design",
    "vector",
    "vector art",
    "vector illustration",
    "video",
    "vintage",
    "visual design",
    "visual identity",
    "water",
    "watercolor",
    "web",
    "web app",
    "web design",
    "web development",
    "website",
    "website design",
    "white",
    "woman",
    "wordpress",
    "yellow",
  ];

  await db.insert(tags).values(tagData.map((tag) => ({ name: tag })));
};

